[package]
name = "ss-local"
version = "0.1.0"
authors = ["simacuo <noemail@anybox.com>"]
edition = "2018"

[dependencies]
mio = "0.6"
slab = "0.4"
log = "0.4"
chrono = "0.4"
log4rs = "0.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
ring = "0.13"
rand = "0.6"
openssl = "0.10"
md-5 = "0.8"
digest = "0.8"
bytes = "0.4"
sodiumoxide = "0.2"
romio = "0.3.0-alpha.1"

[dependencies.futures]
version = "0.3.0-alpha.12"
package = "futures-preview"



