[package]
name = "ss-local"
version = "0.1.0"
authors = ["simacuo <noemail@anybox.com>"]
edition = "2018"

[dependencies]
mio = "0.6"
slab = "0.4"
log = "0.4"
chrono = "0.4"
log4rs = "0.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
ring = "0.13"



